<?php

use NoTee\NodeFactory;
use NoTee\URL;
use NoTee\RawAttribute;

NodeFactory::$globalFactory = new NodeFactory();

function _a() { return NodeFactory::$globalFactory->create(NodeFactory::A, func_get_args()); }
function _abbr() { return NodeFactory::$globalFactory->create(NodeFactory::ABBR, func_get_args()); }
function _acronym() { return NodeFactory::$globalFactory->create(NodeFactory::ACRONYM, func_get_args()); }
function _address() { return NodeFactory::$globalFactory->create(NodeFactory::ADDRESS, func_get_args()); }
function _applet() { return NodeFactory::$globalFactory->create(NodeFactory::APPLET, func_get_args()); }
function _area() { return NodeFactory::$globalFactory->create(NodeFactory::AREA, func_get_args()); }
function _article() { return NodeFactory::$globalFactory->create(NodeFactory::ARTICLE, func_get_args()); }
function _aside() { return NodeFactory::$globalFactory->create(NodeFactory::ASIDE, func_get_args()); }
function _audio() { return NodeFactory::$globalFactory->create(NodeFactory::AUDIO, func_get_args()); }
function _base() { return NodeFactory::$globalFactory->create(NodeFactory::BASE, func_get_args()); }
function _basefont() { return NodeFactory::$globalFactory->create(NodeFactory::BASEFONT, func_get_args()); }
function _b() { return NodeFactory::$globalFactory->create(NodeFactory::B, func_get_args()); }
function _bdo() { return NodeFactory::$globalFactory->create(NodeFactory::BDO, func_get_args()); }
function _bgsound() { return NodeFactory::$globalFactory->create(NodeFactory::BGSOUND, func_get_args()); }
function _big() { return NodeFactory::$globalFactory->create(NodeFactory::BIG, func_get_args()); }
function _blink() { return NodeFactory::$globalFactory->create(NodeFactory::BLINK, func_get_args()); }
function _blockquote() { return NodeFactory::$globalFactory->create(NodeFactory::BLOCKQUOTE, func_get_args()); }
function _body() { return NodeFactory::$globalFactory->create(NodeFactory::BODY, func_get_args()); }
function _br() { return NodeFactory::$globalFactory->create(NodeFactory::BR, func_get_args()); }
function _button() { return NodeFactory::$globalFactory->create(NodeFactory::BUTTON, func_get_args()); }
function _canvas() { return NodeFactory::$globalFactory->create(NodeFactory::CANVAS, func_get_args()); }
function _caption() { return NodeFactory::$globalFactory->create(NodeFactory::CAPTION, func_get_args()); }
function _center() { return NodeFactory::$globalFactory->create(NodeFactory::CENTER, func_get_args()); }
function _cite() { return NodeFactory::$globalFactory->create(NodeFactory::CITE, func_get_args()); }
function _code() { return NodeFactory::$globalFactory->create(NodeFactory::CODE, func_get_args()); }
function _col() { return NodeFactory::$globalFactory->create(NodeFactory::COL, func_get_args()); }
function _colgroup() { return NodeFactory::$globalFactory->create(NodeFactory::COLGROUP, func_get_args()); }
function _command() { return NodeFactory::$globalFactory->create(NodeFactory::COMMAND, func_get_args()); }
function _datalist() { return NodeFactory::$globalFactory->create(NodeFactory::DATALIST, func_get_args()); }
function _dd() { return NodeFactory::$globalFactory->create(NodeFactory::DD, func_get_args()); }
function _del() { return NodeFactory::$globalFactory->create(NodeFactory::DEL, func_get_args()); }
function _details() { return NodeFactory::$globalFactory->create(NodeFactory::DETAILS, func_get_args()); }
function _dfn() { return NodeFactory::$globalFactory->create(NodeFactory::DFN, func_get_args()); }
function _div() { return NodeFactory::$globalFactory->create(NodeFactory::DIV, func_get_args()); }
function _dl() { return NodeFactory::$globalFactory->create(NodeFactory::DL, func_get_args()); }
function _dt() { return NodeFactory::$globalFactory->create(NodeFactory::DT, func_get_args()); }
function _embed() { return NodeFactory::$globalFactory->create(NodeFactory::EMBED, func_get_args()); }
function _em() { return NodeFactory::$globalFactory->create(NodeFactory::EM, func_get_args()); }
function _fieldset() { return NodeFactory::$globalFactory->create(NodeFactory::FIELDSET, func_get_args()); }
function _figcaption() { return NodeFactory::$globalFactory->create(NodeFactory::FIGCAPTION, func_get_args()); }
function _figure() { return NodeFactory::$globalFactory->create(NodeFactory::FIGURE, func_get_args()); }
function _font() { return NodeFactory::$globalFactory->create(NodeFactory::FONT, func_get_args()); }
function _footer() { return NodeFactory::$globalFactory->create(NodeFactory::FOOTER, func_get_args()); }
function _form() { return NodeFactory::$globalFactory->create(NodeFactory::FORM, func_get_args()); }
function _frame() { return NodeFactory::$globalFactory->create(NodeFactory::FRAME, func_get_args()); }
function _frameset() { return NodeFactory::$globalFactory->create(NodeFactory::FRAMESET, func_get_args()); }
function _h1() { return NodeFactory::$globalFactory->create(NodeFactory::H1, func_get_args()); }
function _h2() { return NodeFactory::$globalFactory->create(NodeFactory::H2, func_get_args()); }
function _h3() { return NodeFactory::$globalFactory->create(NodeFactory::H3, func_get_args()); }
function _h4() { return NodeFactory::$globalFactory->create(NodeFactory::H4, func_get_args()); }
function _h5() { return NodeFactory::$globalFactory->create(NodeFactory::H5, func_get_args()); }
function _h6() { return NodeFactory::$globalFactory->create(NodeFactory::H6, func_get_args()); }
function _header() { return NodeFactory::$globalFactory->create(NodeFactory::HEADER, func_get_args()); }
function _head() { return NodeFactory::$globalFactory->create(NodeFactory::HEAD, func_get_args()); }
function _hgroup() { return NodeFactory::$globalFactory->create(NodeFactory::HGROUP, func_get_args()); }
function _hr() { return NodeFactory::$globalFactory->create(NodeFactory::HR, func_get_args()); }
function _NodeFactory() { return NodeFactory::$globalFactory->create(NodeFactory::NodeFactory, func_get_args()); }
function _iframe() { return NodeFactory::$globalFactory->create(NodeFactory::IFRAME, func_get_args()); }
function _i() { return NodeFactory::$globalFactory->create(NodeFactory::I, func_get_args()); }
function _img() { return NodeFactory::$globalFactory->create(NodeFactory::IMG, func_get_args()); }
function _input() { return NodeFactory::$globalFactory->create(NodeFactory::INPUT, func_get_args()); }
function _ins() { return NodeFactory::$globalFactory->create(NodeFactory::INS, func_get_args()); }
function _isindex() { return NodeFactory::$globalFactory->create(NodeFactory::ISINDEX, func_get_args()); }
function _kbd() { return NodeFactory::$globalFactory->create(NodeFactory::KBD, func_get_args()); }
function _keygen() { return NodeFactory::$globalFactory->create(NodeFactory::KEYGEN, func_get_args()); }
function _label() { return NodeFactory::$globalFactory->create(NodeFactory::LABEL, func_get_args()); }
function _legend() { return NodeFactory::$globalFactory->create(NodeFactory::LEGEND, func_get_args()); }
function _li() { return NodeFactory::$globalFactory->create(NodeFactory::LI, func_get_args()); }
function _link() { return NodeFactory::$globalFactory->create(NodeFactory::LINK, func_get_args()); }
function _listing() { return NodeFactory::$globalFactory->create(NodeFactory::LISTING, func_get_args()); }
function _map() { return NodeFactory::$globalFactory->create(NodeFactory::MAP, func_get_args()); }
function _mark() { return NodeFactory::$globalFactory->create(NodeFactory::MARK, func_get_args()); }
function _marquee() { return NodeFactory::$globalFactory->create(NodeFactory::MARQUEE, func_get_args()); }
function _math() { return NodeFactory::$globalFactory->create(NodeFactory::MATH, func_get_args()); }
function _menu() { return NodeFactory::$globalFactory->create(NodeFactory::MENU, func_get_args()); }
function _meta() { return NodeFactory::$globalFactory->create(NodeFactory::META, func_get_args()); }
function _meter() { return NodeFactory::$globalFactory->create(NodeFactory::METER, func_get_args()); }
function _nav() { return NodeFactory::$globalFactory->create(NodeFactory::NAV, func_get_args()); }
function _nextid() { return NodeFactory::$globalFactory->create(NodeFactory::NEXTID, func_get_args()); }
function _nobr() { return NodeFactory::$globalFactory->create(NodeFactory::NOBR, func_get_args()); }
function _noembed() { return NodeFactory::$globalFactory->create(NodeFactory::NOEMBED, func_get_args()); }
function _noframes() { return NodeFactory::$globalFactory->create(NodeFactory::NOFRAMES, func_get_args()); }
function _noscript() { return NodeFactory::$globalFactory->create(NodeFactory::NOSCRIPT, func_get_args()); }
function _object() { return NodeFactory::$globalFactory->create(NodeFactory::OBJECT, func_get_args()); }
function _ol() { return NodeFactory::$globalFactory->create(NodeFactory::UOL, func_get_args()); }
function _optgroup() { return NodeFactory::$globalFactory->create(NodeFactory::OPTGROUP, func_get_args()); }
function _option() { return NodeFactory::$globalFactory->create(NodeFactory::OPTION, func_get_args()); }
function _output() { return NodeFactory::$globalFactory->create(NodeFactory::OUTPUT, func_get_args()); }
function _param() { return NodeFactory::$globalFactory->create(NodeFactory::PARAM, func_get_args()); }
function _plaintext() { return NodeFactory::$globalFactory->create(NodeFactory::PLAINTEXT, func_get_args()); }
function _p() { return NodeFactory::$globalFactory->create(NodeFactory::P, func_get_args()); }
function _pre() { return NodeFactory::$globalFactory->create(NodeFactory::PRE, func_get_args()); }
function _progress() { return NodeFactory::$globalFactory->create(NodeFactory::PROGRESS, func_get_args()); }
function _q() { return NodeFactory::$globalFactory->create(NodeFactory::Q, func_get_args()); }
function _rp() { return NodeFactory::$globalFactory->create(NodeFactory::RP, func_get_args()); }
function _rt() { return NodeFactory::$globalFactory->create(NodeFactory::RT, func_get_args()); }
function _ruby() { return NodeFactory::$globalFactory->create(NodeFactory::RUBY, func_get_args()); }
function _samp() { return NodeFactory::$globalFactory->create(NodeFactory::SAMP, func_get_args()); }
function _script() { return NodeFactory::$globalFactory->create(NodeFactory::SCRIPT, func_get_args()); }
function _section() { return NodeFactory::$globalFactory->create(NodeFactory::SECTION, func_get_args()); }
function _select() { return NodeFactory::$globalFactory->create(NodeFactory::SELECT, func_get_args()); }
function _small() { return NodeFactory::$globalFactory->create(NodeFactory::SMALL, func_get_args()); }
function _source() { return NodeFactory::$globalFactory->create(NodeFactory::SOURCE, func_get_args()); }
function _spacer() { return NodeFactory::$globalFactory->create(NodeFactory::SPACER, func_get_args()); }
function _span() { return NodeFactory::$globalFactory->create(NodeFactory::SPAN, func_get_args()); }
function _s() { return NodeFactory::$globalFactory->create(NodeFactory::S, func_get_args()); }
function _strike() { return NodeFactory::$globalFactory->create(NodeFactory::STRIKE, func_get_args()); }
function _strong() { return NodeFactory::$globalFactory->create(NodeFactory::STRONG, func_get_args()); }
function _style() { return NodeFactory::$globalFactory->create(NodeFactory::STYLE, func_get_args()); }
function _sub() { return NodeFactory::$globalFactory->create(NodeFactory::SUB, func_get_args()); }
function _sup() { return NodeFactory::$globalFactory->create(NodeFactory::SUP, func_get_args()); }
function _summary() { return NodeFactory::$globalFactory->create(NodeFactory::SUMMARY, func_get_args()); }
function _svg() { return NodeFactory::$globalFactory->create(NodeFactory::SVG, func_get_args()); }
function _table() { return NodeFactory::$globalFactory->create(NodeFactory::TABLE, func_get_args()); }
function _tbody() { return NodeFactory::$globalFactory->create(NodeFactory::TBODY, func_get_args()); }
function _td() { return NodeFactory::$globalFactory->create(NodeFactory::TD, func_get_args()); }
function _textarea() { return NodeFactory::$globalFactory->create(NodeFactory::TEXTAREA, func_get_args()); }
function _tfoot() { return NodeFactory::$globalFactory->create(NodeFactory::TFOOT, func_get_args()); }
function _thead() { return NodeFactory::$globalFactory->create(NodeFactory::THEAD, func_get_args()); }
function _th() { return NodeFactory::$globalFactory->create(NodeFactory::TH, func_get_args()); }
function _time() { return NodeFactory::$globalFactory->create(NodeFactory::TIME, func_get_args()); }
function _title() { return NodeFactory::$globalFactory->create(NodeFactory::TITLE, func_get_args()); }
function _tr() { return NodeFactory::$globalFactory->create(NodeFactory::TR, func_get_args()); }
function _tt() { return NodeFactory::$globalFactory->create(NodeFactory::TT, func_get_args()); }
function _ul() { return NodeFactory::$globalFactory->create(NodeFactory::UL, func_get_args()); }
function _u() { return NodeFactory::$globalFactory->create(NodeFactory::U, func_get_args()); }
function _var() { return NodeFactory::$globalFactory->create(NodeFactory::_VAR, func_get_args()); }
function _video() { return NodeFactory::$globalFactory->create(NodeFactory::VIDEO, func_get_args()); }
function _wbr() { return NodeFactory::$globalFactory->create(NodeFactory::WBR, func_get_args()); }
function _xmp() { return NodeFactory::$globalFactory->create(NodeFactory::XMP, func_get_args()); }

function _text($text) { return NodeFactory::$globalFactory->text($text); }
function _raw($text) { return NodeFactory::$globalFactory->raw($text); }

function _rawAttr($text) { return new RawAttribute($text); }
function _urlAttr($base, $parameters) { return new URL($base, $parameters); }
